name: dotnet package

on: push

jobs:
  build:
    runs-on: ${{ matrix.machine }}
    strategy:
      matrix:
        include:
        - machine: macos-latest
          runtime: osx-x64
        - machine: ubuntu-latest 
          runtime: linux-x64
        - machine: windows-latest
          runtime: win-x64
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 6
        uses: actions/setup-dotnet
        with:
          dotnet-version: "6.0.x"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore